config/routes.rb
Rails.application.routes.draw do
  match 'sources/update_by_text_and_lang' => 'sources#update_by_text_and_lang', via: [:put, :patch]
  resources :sources
  resources :translations, only: 'destroy'

  get 'search', to: 'sources#search'

  root to: 'sources#index'
end

app/models/locale_validator.rb
require 'iso'

class LocaleValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value.blank? || ISO::Tag.new(value).valid?
      record.errors[attribute] << (options[:message] || 'is not valid')
    end
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :translations, dependent: :destroy, inverse_of: :source
  accepts_nested_attributes_for :translations

  validates :text, presence: true, uniqueness: { scope: :language, if: ->(s) { s.language? } }
  validates :language, presence: true, locale: true

  def self.supported_languages
    %w(en cs da de el es fi fr it nl no pl pt sv tr)
  end

  def self.search(query)
    rs = Source
    rs = where('text LIKE ?', "%#{query[:text]}%") unless query[:text].blank?
    rs = rs.where(language: query[:language]) unless query[:language].blank?
    rs.paginate(page: query[:page], per_page: query[:per_page])
  end
end

app/models/source_observer.rb
class SourceObserver < ActiveRecord::Observer # rubocop:disable Style/Documentation
  def before_update(source)
    return unless source.translations.any?

    TranslationCache.new.update(source.translations)
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :source, inverse_of: :translations

  validates :text, presence: true
  validates :language, presence: true, locale: true
  validates :language, uniqueness: { scope: :source_id, if: ->(t) { t.source } }

  default_scope -> { order('language asc') }
end

app/models/translation_cache.rb
require 'i18n'

# In an attempt to insulate itself from I18n specifics (though I18n doesn't make this easy) this class
# goes a bit out of its way to use I18n's interface instead the raw  key/value store.
class TranslationCache
  CacheError = Class.new(StandardError)

  def update(translations)
    Array(translations).each { |t| store_translation(t) }
  rescue => e
    raise CacheError, e.message
  end

  def delete(translations)
    return unless delete_supported?

    Array(translations).each do |t|
      next unless t.source && t.language
      delete_from_cache(t.language, t.source.text)
    end
  rescue => e
    raise CacheError, e.message
  end

  private

  def store_translation(t)
    return unless t.source

    if changed?(t)
      lang = t.language_changed?    ? t.language_change[0]    : t.language
      text = t.source.text_changed? ? t.source.text_change[0] : t.source.text

      delete_from_cache(lang, text)
    end

    I18n.backend.store_translations t.language, t.source.text => t.text
  end

  def changed?(t)
    # If the backend doesn't delete, then we don't care if it has changed
    delete_supported? && (t.language_changed? || t.source.text_changed?)
  end

  def cache
    return @cache if defined?(@cache)

    be = Array( I18n.backend.respond_to?(:backends) ? I18n.backend.backends : I18n.backend ).
         find { |b| b.is_a?(I18n::Backend::KeyValue) }

    @cache = be.respond_to?(:store) ? be.store : nil
  end

  def key(locale, key)
    bef = I18n::Backend::Flatten
    sprintf '%s%s%s', locale, bef::FLATTEN_SEPARATOR, bef.escape_default_separator(key)
  end

  def delete_supported?
    cache.respond_to?(:del)
  end

  def delete_from_cache(lang, text)
    cache.del(key(lang, text))
  end
end

app/models/translation_observer.rb
class TranslationObserver < ActiveRecord::Observer
  def before_save(translation)
    TranslationCache.new.update(translation)
  end

  def before_destroy(translation)
    TranslationCache.new.delete(translation)
  end
end

app/controllers/application_controller.rb
require 'bh-flash'

# application controller
class ApplicationController < ActionController::Base
  helper Bh::Flash

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from TranslationCache::CacheError do |ex|
    logger.error(ex)
    flash.now[:alert] = "Failed to save translation in the cache: #{ex}"
    render action: action_name
  end
end

app/controllers/sources_controller.rb
# Sources controller to take care of CRUD operations
class SourcesController < ApplicationController
  before_action :populate_source, only: [:edit, :show, :update, :destroy]

  def index
    @sources = Source.paginate(page: params[:page], per_page: params[:per_page])
  end

  def search
    if params[:text].blank? && params[:language].blank?
      redirect_to sources_path
      return
    end

    @sources = Source.search(params)
  end

  def new
    # We set attributes here because we allow sources to be created from a search with 0 results.
    @source = Source.new(params.permit(source: [:text])[:source])
    @source.translations.build
  end

  def create
    @source = Source.new(source_params)
    if @source.save
      redirect_to @source, notice: 'Source and translations created'
    else
      save_failed!
      render action: 'new'
    end
  end

  def export
    TranslationFormats::PO.export(params[:language].presence || "en")
  end

  def update
    if @source.update_attributes(source_params)
      redirect_to @source, notice: 'Source and translations updated'
    else
      save_failed!
      render action: 'edit'
    end
  end

  def destroy
    @source.destroy
    redirect_to sources_url, notice: 'Source and translations deleted'
  end

  private

  def save_failed!
    flash.now[:error] = 'Save Failed! Correct the errors below and try again.'
  end

  def populate_source
    @source = Source.includes(:translations).find(params[:id])
  end

  def source_params
    params.require(:source)
      .permit(:language, :text, :context, :original,
	      translations_attributes: [:language, :text, :context, :id, :source_id])
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def destroy
    # TODO: errors
    @translation = Translation.find(params[:id])
    @translation.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/source_helper.rb
module SourceHelper
  def current_search_query(params)
    q = []
    q << sprintf('language "%s"', params[:language]) unless params[:language].blank?
    q << sprintf('text "%s"', truncate(params[:text], length: 75)) unless params[:text].blank?
    q.to_sentence.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Translation Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.selectunique.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= navbar do %>
    <%= vertical do %>
      <%= link_to root_path do %>
        <%- if File.exists?('logo.png') %>
	  <%= image_tag 'logo.png', :size => '25x25' %>
        <% end %>
	Translation Manager
      <% end %>
    <% end %>

    <%= horizontal class: 'navbar-right' do %>
      <%= link_to 'Create', new_source_path, class: 'btn btn-sm btn-success navbar-btn' %>
    <% end %>

    <%= nav class: 'navbar-right' do %>
      <%= link_to 'Search', '#', data: { toggle: 'modal', target: '#modal-search' } %>
      <%= link_to 'Sources', sources_path %>
    <% end %>
  <% end %>

  <div class="container">
    <%= render_flash_messages %>
    <%= yield %>
  </div>

  <%= render 'shared/search' %>
</body>
</html>

app/views/shared/_search.html.erb
<div class="modal fade" id="modal-search" tabindex="-1" role="dialog" aria-labelledby="label-modal" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
	  <span aria-hidden="true">×</span><span class="sr-only">Close</span>
	</button>
	<h4 class="modal-title" id="label-modal">Search</h4>
      </div>

      <%= form_tag search_path, method: 'get' do %>
	<div class="modal-body">
	  <div class='form-group'>
	    <label for='language'>Language</label>
	    <%= select_tag :language, options_for_select(Source.supported_languages, params[:language] || 'en'), class: 'form-control' %>
	  </div>
	  <div class='form-group'>
	    <label for='text'>Text</label>
	    <%= text_area_tag :text, params[:text], class: 'form-control' %>
	  </div>
	</div>
	<div class="modal-footer">
	  <%= submit_tag 'Go', class: 'btn btn-primary' %>
	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_toggle_wysiwyg.html.erb
<div class="editor disabled">
  Editor:
  <%= link_to 'On', '#', class: 'on btn btn-xs btn-info' %>
  <%= link_to 'Off', '#', class: 'off btn btn-xs btn-default' %>
</div>

app/views/sources/_form.html.erb
<%= form_for @source, layout: :basic do |f| %>
  <%= f.select :language , Source.supported_languages %>
  <%= f.text_field :context %>
  <%= f.text_area :text %>

  <h3>Translations <!--small>(<%= @source.translations.size %>)</small--></h3>
  <div class="pull-left">
    <%= link_to 'Add New Translation', '#', class: 'add-translation btn btn-success btn-sm' %>
  </div>
  <table id='translationFields' class='table'>
    <thead>
      <tr>
	<th>Language</th>
	<th colspan="2">Text</th>
      </tr>
    </thead>

    <tbody>
	<%= f.fields_for :translations, layout: :inline, fieldset: false, include_id: false, errors: { messages: true } do |translation| %>
        <tr id="<%= dom_id(translation.object) %>" class="translation">
	  <td>
	    <%= translation.select :language, Source.supported_languages %>
	    <%= translation.object.errors.to_a.to_sentence %>
	  </td>
	  <td>
	    <%= translation.text_area :text, class: 'tinymce' %>
	  </td>
	  <td>
	    <% if translation.object.new_record? %>
	      <%= link_to 'Delete', '#', :class => 'remove btn btn-xs btn-danger' %>
	    <% else %>
	      <%= link_to 'Delete', translation.object, :remote => true, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %>
	    <% end %>
	    <%= translation.hidden_field :id %>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
  <div class="pull-left">
    <%= link_to 'Add New Translation', '#', class: 'add-translation btn btn-success btn-sm' %>
  </div>
  <div class="pull-right">
    <% if @source.id %>
      <%= link_to 'Cancel', source_path(@source), class: 'btn btn-danger', data: { confirm: 'Are you sure you want to discard your changes?' } %>
    <% end %>
    <%= f.submit %>
  </div>
  <%= javascript_tag :id => 'translation-row', :type => 'text/x-html' do %>
    <%= f.fields_for :translations, Translation.new, layout: :inline, fieldset: false, include_id: false  do |translation| %>
      <tr class="translation">
	<td>
	  <%= translation.select :language, Source.supported_languages %>
	</td>
	<td>
	  <%= translation.text_area :text %>
	</td>
	<td>
	  <%= link_to 'Delete', '#', :class => 'remove btn btn-xs btn-danger' %>
	</td>
      </tr>
    <% end %>
  <% end %>
<% end %>

app/views/sources/_sources.html.erb
<table class='table table-hover'>
  <thead>
    <tr>
      <th>Language</th>
      <th colspan="2">Text</th>
    </tr>
  </thead>

  <tbody>
    <% sources.each do |source| %>
      <tr id="<%= dom_id(source) %>" class="source">
	<td><%= source.language %></td>
	<td><%= source.text.html_safe %></td>
	<td>
	  <%= link_to 'View', source %>
	  &#183;
	  <%= link_to 'Edit', edit_source_path(source), 'data-no-turbolink' => 'true' %>
	  &#183;
	  <%= link_to 'Delete', source, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate sources, renderer: BootstrapPagination::Rails %>

app/views/sources/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'shared/toggle_wysiwyg' %>

    <h2>Edit Source</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/sources/index.html.erb
<h2>Sources</h2>

<% if @sources.none? %>
  <p>No sources have been created. <%= link_to 'Create one', new_source_path %>!</p>
<% else %>
  <%= render 'sources', :sources => @sources %>
<% end %>

app/views/sources/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'shared/toggle_wysiwyg' %>

    <h2>New Source</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/sources/search.html.erb
<h2>Search: <span style="font-weight:normal;font-size:0.9em"><%= current_search_query(params) %></span></h2>

<% if @sources.none? %>
  <p>No sources found. Would you like to <%= link_to 'create a source from this search', new_source_path(:source => { :text => params[:text] }) %>?</p>
<% else %>
  <%= render 'sources', :sources => @sources %>
<% end %>

app/views/sources/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="pull-rightX">
      <%= form_for @source, method: 'delete', html: { style: 'display: inline' } do |f| %>
        <%= f.submit 'Delete', class: 'btn btn-xs btn-danger'  %>
      <% end %>
      &#183;
      <%= link_to 'Edit', edit_source_path(@source) %>
    </div>

    <h2>
      Source |
      <small>
	<%= @source.language %>
	<% if @source.context.present? %>
	  &#183; <%= @source.context %>
	<% end %>
      </small>
    </h2>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <blockquote>
      <%= @source.text.html_safe %>
    </blockquote>

    <% if @source.context.present? %>
      <p>
	<strong>Context:</strong>
	<%= @source.context %>
      </p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h3>Translations <!--small>(<%= @source.translations.size %>)</small--></h3>
    <table class="table">
      <thead>
	<tr>
	  <th>Language</th>
	  <th colspan="2">Text</th>
	</tr>
      </thead>

      <tbody>
	<% @source.translations.each do |translation| %>
	  <tr id="<%= dom_id(translation) %>" class="translation">
	    <td><%= translation.language %></td>
	    <td><%= translation.text.html_safe %></td>
	    <td>
	      <%= link_to 'Delete', translation, remote: true, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/translations/destroy.js.erb
$('#<%= dom_id(@translation) %>').remove();